man/sd_journal_next: fix argument in example
The example does not compile, it fails with:

error: passing argument 3 of ‘sd_journal_get_data’ from incompatible
pointer type

Cast to (const void **) to avoid this.

(cherry picked from commit 8959ae0d4cc7921293a21182693b7d953f6cce9b)